### ISSUE TITLE
booking appointment feature

### ISSUE THREAD

**Issue by sirkenedy** [InventorsDev/sdg-006-backend#22]
### Appointment booking feature which enables user to book appointment with doctors

**_TASK LIST_**

- [x] create migrations ,model and controllers
- [x] update the controller
- [x] make the endpoints available by adding routes to 

> routes/api.php file

- [x] Testing all newly created endpoints with postman
- [x] Deployment to heroku via master branch
- [x] Testing of endpoints on live server( i.e After deployment)
