### ISSUE TITLE
User drop reviews and rate doctors after the end of each appoinments/meetings  feature -- MedHouse

### ISSUE THREAD

**Issue by sirkenedy** [InventorsDev/sdg-006-backend#23]
### This feature will enable User(Patients) of the system drop their review after each meetings/appointments with a doctor and also drop ratings -- MedHouse
**_TASK LIST_**
- [ ] create necessary migrations, Models, interface , repositories and controller fiiles needed
- [ ] Install and configure [willvincent/laravel-rateable package](https://github.com/willvincent/laravel-rateable) which will be used to add rating feature to the application
- [ ] Finishing up the task
- [ ] Testing and bug fixes
- [ ] deployment to live server( i.e when pushed to heroku)
- [ ] Testing of newly added feature on live server and bug fixes
