### ISSUE TITLE
Create endpoints for fetching specialist and patients

### ISSUE THREAD

**Issue by sirkenedy** [InventorsDev/sdg-006-backend#24]
### This feature involves making available endpoints for fetching specialist and patients information
**TASK LIST**

- [x] install and configure [laravel spatie permission package](https://github.com/spatie/laravel-permission)
- [x] create Patient and specialist controllers
- [x] implement necessary methods in each of the controller
- [x] add new endpoints by editing the

> route/api.php file

- [x] Test all endpoints
- [x] fix bugs and issues
- [x] Finishing up task and deployment
